name: adventofcode2017

dependencies:
- base
- array
- split
- parsec

library:
  source-dirs: src

executables:
  adventofcode2017:
    source-dirs: app
    main: Main.hs
    dependencies:
      - adventofcode2017
