import Data.Bits
import Data.Int
import Prelude hiding (and, or, not, id)

rshift = shiftR
lshift = shiftL
and = (.&.)
or = (.|.)

not :: Int16 -> Int16
not = complement

solution = a
    where
        ls = lf `and` lq
        jn = iu `rshift` 1
        bv = bo `or` bu
        hc = gj `rshift` 1
        eu = et `rshift` 2
        by = bv `and` bx
        iu = is `or` it
        o = b `or` n
        gg = gf `or` ge
        ku = not kt
        ed = ea `and` eb
        ks = kl `or` kr
        hl = hi `and` hk
        ax = au `and` av
        lg = lf `rshift` 2
        df = dd `rshift` 3
        fc = eu `and` fa
        di = df `and` dg
        it = ip `lshift` 15
        em = not el
        ff = et `or` fe
        fn = fj `lshift` 15
        u = t `or` s
        ma = ly `or` lz
        kr = ko `and` kq
        fy = not fx
        fm = et `rshift` 1
        fb = eu `or` fa
        de = dd `rshift` 2
        gp = not go
        ke = kb `and` kd
        hi = hg `or` hh
        kg = jm `lshift` 1
        co = not cn
        jq = jp `rshift` 2
        js = jp `rshift` 5
        ip = 1 `and` io
        es = eo `lshift` 15
        jk = 1 `and` jj
        j = g `and` i
        ck = ci `rshift` 3
        gq = gn `and` gp
        fv = fs `and` fu
        lm = lj `and` ll
        jo = jk `lshift` 15
        iw = iu `rshift` 3
        ij = not ii
        cd = 1 `and` cc
        bp = bn `rshift` 3
        gx = not gw
        fu = not ft
        jp = jn `or` jo
        jc = iv `or` jb
        hw = hv `or` hu
        b = 16076
        gm = gj `rshift` 5
        ht = hq `and` hs
        er = dy `rshift` 1
        ap = ao `or` an
        lf = ld `or` le
        ce = bk `lshift` 1
        cc = bz `and` cb
        bm = bi `lshift` 15
        io = il `and` in'
        ai = af `and` ah
        bl = as `rshift` 1
        lh = lf `rshift` 3
        et = er `or` es
        ay = not ax
        db = ci `rshift` 1
        fg = et `and` fe
        ln = lg `or` lm
        n = k `and` m
        ia = hz `rshift` 2
        lb = kh `lshift` 1
        ez = not ey
        dj = not di
        eg = dz `or` ef
        a = lx
        ja = not iz
        hd = gz `lshift` 15
        cf = ce `or` cd
        ft = fq `and` fr
        bb = at `and` az
        hb = ha `or` gz
        fx = fp `and` fv
        gc = not gb
        ii = ia `and` ig
        gn = gl `or` gm
        c = 0
        cb = not ca
        cg = bn `rshift` 1
        t = c `lshift` 1
        iy = iw `or` ix
        kh = kg `or` kf
        ek = dy `or` ej
        kp = km `and` kn
        fd = not fc
        ib = hz `rshift` 3
        dr = not dq
        fh = not fg
        dz = dy `rshift` 2
        kl = kk `rshift` 2
        fj = 1 `and` fi
        hs = not hr
        ki = jp `rshift` 1
        bn = bl `or` bm
        gz = 1 `and` gy
        gu = gr `and` gt
        dd = db `or` dc
        dl = de `or` dk
        av = as `rshift` 5
        li = lf `rshift` 5
        hp = hm `and` ho
        ci = cg `or` ch
        gw = gj `and` gu
        gi = ge `lshift` 15
        g = e `or` f
        fw = fp `or` fv
        fe = fb `and` fd
        ch = cd `lshift` 15
        v = b `rshift` 1
        ba = at `or` az
        bo = bn `rshift` 2
        lk = lh `and` li
        do' = dl `and` dn
        ej = eg `and` ei
        fa = ex `and` ez
        kq = not kp
        ll = not lk
        ak = x `and` ai
        kb = jp `or` ka
        je = not jd
        jb = iy `and` ja
        jr = jp `rshift` 3
        ga = fo `or` fz
        dh = df `or` dg
        gk = gj `rshift` 2
        gv = gj `or` gu
        ji = not jh
        bj = ap `lshift` 1
        lt = not ls
        jl = ir `lshift` 1
        ca = bn `and` by
        lz = lv `lshift` 15
        bd = ba `and` bc
        dc = cy `lshift` 15
        lq = ln `and` lp
        aq = x `rshift` 1
        gr = gk `or` gq
        ky = not kx
        jj = jg `and` ji
        bz = bn `or` by
        gf = fl `lshift` 1
        br = bp `or` bq
        hq = he `or` hp
        ew = et `rshift` 5
        iv = iu `rshift` 2
        go = gl `and` gm
        aj = x `or` ai
        he = hc `or` hd
        lo = lg `and` lm
        lj = lh `or` li
        du = da `lshift` 1
        fp = fo `rshift` 2
        gs = gk `and` gq
        bk = bj `or` bi
        lr = lf `or` lq
        cr = cj `and` cp
        hy = hu `lshift` 15
        bi = 1 `and` bh
        fq = fo `rshift` 3
        lp = not lo
        iq = hw `lshift` 1
        dw = dd `rshift` 1
        dx = dt `lshift` 15
        el = dy `and` ej
        ar = an `lshift` 15
        as = aq `or` ar
        s = 1 `and` r
        fz = fw `and` fy
        in' = not im
        ev = et `rshift` 3
        dt = 1 `and` ds
        ef = ec `and` ee
        al = not ak
        jm = jl `or` jk
        eo = 1 `and` en
        lc = lb `or` la
        jh = iu `and` jf
        ix = iu `rshift` 5
        bw = bo `and` bu
        da = cz `or` cy
        jd = iv `and` jb
        iz = iw `and` ix
        ly = lf `rshift` 1
        jg = iu `or` jf
        dn = not dm
        lx = lw `or` lv
        ha = gg `lshift` 1
        lu = lr `and` lt
        fo = fm `or` fn
        hg = he `rshift` 3
        am = aj `and` al
        la = 1 `and` kz
        eb = dy `rshift` 5
        jf = jc `and` je
        cp = cm `and` co
        gy = gv `and` gx
        ex = ev `or` ew
        kc = jp `and` ka
        fl = fk `or` fj
        ea = dy `rshift` 3
        bt = not bs
        ah = not ag
        eh = dz `and` ef
        cz = cf `lshift` 1
        cw = not cv
        cy = 1 `and` cx
        dm = de `and` dk
        cn = ck `and` cl
        aa = x `rshift` 5
        ep = dv `lshift` 1
        hf = he `rshift` 2
        bx = not bw
        cm = ck `or` cl
        bs = bp `and` bq
        be = as `or` bd
        hr = he `and` hp
        ey = ev `and` ew
        lv = 1 `and` lu
        km = kk `rshift` 3
        p = b `and` n
        kd = not kc
        lw = lc `lshift` 1
        ko = km `or` kn
        ig = id `and` if'
        ik = ih `and` ij
        ju = jr `and` js
        cl = ci `rshift` 5
        is = hz `rshift` 1
        kf = 1 `and` ke
        gt = not gs
        az = aw `and` ay
        y = x `rshift` 2
        ae = ab `and` ad
        fi = ff `and` fh
        cv = ci `and` ct
        fk = eq `lshift` 1
        gl = gj `rshift` 3
        ao = u `lshift` 1
        bc = not bb
        hk = not hj
        kz = kw `and` ky
        bf = as `and` bd
        dy = dw `or` dx
        bu = br `and` bt
        kx = kk `and` kv
        eq = ep `or` eo
        hx = he `rshift` 1
        kk = ki `or` kj
        jv = not ju
        en = ek `and` em
        kn = kk `rshift` 5
        ei = not eh
        hz = hx `or` hy
        ec = ea `or` eb
        w = s `lshift` 15
        gh = fo `rshift` 1
        kw = kk `or` kv
        bq = bn `rshift` 5
        ee = not ed
        hu = 1 `and` ht
        cx = cu `and` cw
        f = b `rshift` 5
        kt = kl `and` kr
        ir = iq `or` ip
        cj = ci `rshift` 2
        cq = cj `or` cp
        r = o `and` q
        dg = dd `rshift` 5
        d = b `rshift` 2
        kv = ks `and` ku
        e = b `rshift` 3
        k = d `or` j
        q = not p
        cs = not cr
        dv = du `or` dt
        kj = kf `lshift` 15
        ad = not ac
        fr = fo `rshift` 5
        il = hz `or` ik
        ka = jx `and` jz
        gj = gh `or` gi
        ld = kk `rshift` 1
        ic = hz `rshift` 5
        at = as `rshift` 2
        jz = not jy
        an = 1 `and` am
        cu = ci `or` ct
        hj = hg `and` hh
        jx = jq `or` jw
        x = v `or` w
        le = la `lshift` 15
        dk = dh `and` dj
        ds = dp `and` dr
        jy = jq `and` jw
        aw = au `or` av
        bg = not bf
        ab = z `or` aa
        gd = ga `and` gc
        im = hz `and` ik
        jw = jt `and` jv
        ac = z `and` aa
        jt = jr `or` js
        hv = hb `lshift` 1
        hm = hf `or` hl
        id = ib `or` ic
        fs = fq `or` fr
        ct = cq `and` cs
        ih = ia `or` ig
        dp = dd `or` do'
        l = d `and` j
        ie = ib `and` ic
        au = as `rshift` 3
        bh = be `and` bg
        dq = dd `and` do'
        m = not l
        ge = 1 `and` gd
        ag = y `and` ae
        gb = fo `and` fz
        if' = not ie
        h = e `and` f
        z = x `rshift` 3
        af = y `or` ae
        hn = hf `and` hl
        i = not h
        ho = not hn
        hh = he `rshift` 5

main = print solution 
